/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Repository } from "./Repository";
import { RepositoryCountArgs } from "./RepositoryCountArgs";
import { RepositoryFindManyArgs } from "./RepositoryFindManyArgs";
import { RepositoryFindUniqueArgs } from "./RepositoryFindUniqueArgs";
import { CreateRepositoryArgs } from "./CreateRepositoryArgs";
import { UpdateRepositoryArgs } from "./UpdateRepositoryArgs";
import { DeleteRepositoryArgs } from "./DeleteRepositoryArgs";
import { Commit } from "../../commit/base/Commit";
import { Owner } from "../../owner/base/Owner";
import { Tag } from "../../tag/base/Tag";
import { RepositoryFilterInput } from "../RepositoryFilterInput";
import { RepositorySearchInput } from "../RepositorySearchInput";
import { RepositorySortInput } from "../RepositorySortInput";
import { RepositoryService } from "../repository.service";
@graphql.Resolver(() => Repository)
export class RepositoryResolverBase {
  constructor(protected readonly service: RepositoryService) {}

  async _repositoriesMeta(
    @graphql.Args() args: RepositoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Repository])
  async repositories(
    @graphql.Args() args: RepositoryFindManyArgs
  ): Promise<Repository[]> {
    return this.service.repositories(args);
  }

  @graphql.Query(() => Repository, { nullable: true })
  async repository(
    @graphql.Args() args: RepositoryFindUniqueArgs
  ): Promise<Repository | null> {
    const result = await this.service.repository(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Repository)
  async createRepository(
    @graphql.Args() args: CreateRepositoryArgs
  ): Promise<Repository> {
    return await this.service.createRepository({
      ...args,
      data: {
        ...args.data,

        commit: args.data.commit
          ? {
              connect: args.data.commit,
            }
          : undefined,

        owner: args.data.owner
          ? {
              connect: args.data.owner,
            }
          : undefined,

        tag: args.data.tag
          ? {
              connect: args.data.tag,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Repository)
  async updateRepository(
    @graphql.Args() args: UpdateRepositoryArgs
  ): Promise<Repository | null> {
    try {
      return await this.service.updateRepository({
        ...args,
        data: {
          ...args.data,

          commit: args.data.commit
            ? {
                connect: args.data.commit,
              }
            : undefined,

          owner: args.data.owner
            ? {
                connect: args.data.owner,
              }
            : undefined,

          tag: args.data.tag
            ? {
                connect: args.data.tag,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Repository)
  async deleteRepository(
    @graphql.Args() args: DeleteRepositoryArgs
  ): Promise<Repository | null> {
    try {
      return await this.service.deleteRepository(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Commit, {
    nullable: true,
    name: "commit",
  })
  async getCommit(
    @graphql.Parent() parent: Repository
  ): Promise<Commit | null> {
    const result = await this.service.getCommit(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Owner, {
    nullable: true,
    name: "owner",
  })
  async getOwner(@graphql.Parent() parent: Repository): Promise<Owner | null> {
    const result = await this.service.getOwner(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Tag, {
    nullable: true,
    name: "tag",
  })
  async getTag(@graphql.Parent() parent: Repository): Promise<Tag | null> {
    const result = await this.service.getTag(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Query(() => String)
  async FilterRepositoriesByStars(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.FilterRepositoriesByStars(args);
  }

  @graphql.Query(() => [RepositoryFilterInput])
  async FilterRepositoriesByStarsAction(
    @graphql.Args()
    args: RepositoryFilterInput
  ): Promise<RepositoryFilterInput[]> {
    return this.service.FilterRepositoriesByStarsAction(args);
  }

  @graphql.Query(() => String)
  async SearchRepositories(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.SearchRepositories(args);
  }

  @graphql.Query(() => [RepositorySearchInput])
  async SearchRepositoriesAction(
    @graphql.Args()
    args: RepositorySearchInput
  ): Promise<RepositorySearchInput[]> {
    return this.service.SearchRepositoriesAction(args);
  }

  @graphql.Query(() => String)
  async SortRepositoriesByDateAdded(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.SortRepositoriesByDateAdded(args);
  }

  @graphql.Query(() => [RepositorySortInput])
  async SortRepositoriesByDateAddedAction(
    @graphql.Args()
    args: RepositorySortInput
  ): Promise<RepositorySortInput[]> {
    return this.service.SortRepositoriesByDateAddedAction(args);
  }
}
